# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
